### ISSUE TITLE
Doesn't compile on 2015.1

### ISSUE THREAD

**Issue by alixedi** [maxeler/HybridMiner#1]
cd APP/RunRules/Simulation
make distclean
make build

gives this error:

```
 [java] Error: Could not find or load main class com.maxeler.applibrary.bitcoinminer.HybridMinerManager
```

**Comment by carmenfan** [comment]
Fixed

**Comment by alixedi** [comment]
Now I am getting this:

common/json_wrapper.c:11:23: error: json/json.h: No such file or directory

**Comment by carmenfan** [comment]
you need json-c for this app. 

"External Libraries Required
Please ensure cURL and JSON-C are installed in the machine. To install cURL, run (with root access): yum install curl yum install curl-devel

To install JSON-C, run (with root access): yum install json-c yum install json-c-devel"

**Comment by alixedi** [comment]
:+1:
